dbt_bg_foundation:
  outputs:
    dev:
      dataset: dciciani
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: skyita-da-architects-sandbox
      threads: 1
      type: bigquery
  target: dev